name: Staffy
version: '${project.version}'
main: com.github.pluginsell.staffy.Main
authors: [EggZackley]
description: StaffMode Plugin
website: https://discord.gg/w7ZGPXGpaX
softdepend:
  - LuckPerms
  - Ranky
  - StaffyPunishments
commands:
  clearchat:
    aliases:
      - clearc
      - cchat
      - cc
      - cclear
      - chatclear
      - chatc
  freeze:
    usage: /<command>
  inventorysee:
    aliases:
      - invsee
      - isee
  lockdown:
    aliases:
      - chatlock
      - lockchat
      - chatlockdown
      - lockdownchat
  randomteleport:
    aliases:
      - randomtp
      - rteleport
      - rtp
  staffchat:
    aliases:
      - schat
      - sc
  staffmode:
    aliases:
      - staffm
      - sm
      - smode
      - staff
  unfreeze:
    usage: /<command>
  vanish:
    aliases:
      - v